<?php

use App\Domain\Attendance\Actions\ReconstructAttendanceSessionsAction;
use App\Domain\Attendance\Models\RawAccessEvent;
use App\Domain\Auth\Models\Organization;
use App\Domain\Devices\Actions\IngestRawAccessEventAction;
use App\Domain\Devices\Adapters\SimulatorDeviceAdapter;
use App\Domain\Devices\Models\Credential;
use App\Domain\Devices\Models\CredentialAssignment;
use App\Domain\Devices\Models\Device;
use App\Domain\Devices\Models\Site;
use App\Domain\Employees\Models\Employee;
use App\Domain\Shared\Services\CurrentOrganization;
use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

pest()->group('attendance', 'devices');

/**
 * Audit A04, 01-CRM-Audit-KA.md: „Simulator-ის შედეგები არ უნდა
 * მონაწილეობდეს რეალურ ტაბელსა და ხელფასში."
 *
 * It did. `config/modules/devices.php` defaults `devices.adapter` to
 * `simulator`, the in-app "generate test event" button did not set
 * `ingestion_source` at all (so IngestRawAccessEventAction stamped it
 * `device-connector`, indistinguishable from a real badge read), and nothing
 * in the pipeline — reconstruction, timesheet generation or pay-run
 * calculation — ever looked at provenance. Two clicks of that button
 * therefore produced a real AttendanceSession with real payable minutes,
 * which became a TimesheetLine and then money.
 *
 * These tests run the REAL simulator payload through the REAL ingest action
 * and the REAL reconstruction, because every one of those steps is where the
 * bug actually lived.
 */
beforeEach(function () {
    $this->organization = Organization::factory()->create();
    CurrentOrganization::set($this->organization->id);

    $this->actor = User::factory()->create([
        'organization_id' => $this->organization->id,
        'current_organization_id' => $this->organization->id,
    ]);
    $this->site = Site::factory()->create(['organization_id' => $this->organization->id]);
    $this->device = Device::factory()->create([
        'organization_id' => $this->organization->id,
        'site_id' => $this->site->id,
    ]);
    $this->employee = Employee::factory()->create(['organization_id' => $this->organization->id]);
    $this->credential = Credential::factory()->create(['organization_id' => $this->organization->id]);
    CredentialAssignment::factory()->create([
        'organization_id' => $this->organization->id,
        'credential_id' => $this->credential->id,
        'employee_id' => $this->employee->id,
        'valid_from' => now()->subYear(),
    ]);

    $this->day = Carbon::parse('2026-09-21 00:00:00', 'UTC');

    $this->reconstruct = fn () => app(ReconstructAttendanceSessionsAction::class)->handle(
        $this->employee,
        $this->day->copy()->startOfDay(),
        $this->day->copy()->endOfDay(),
        $this->actor,
    );
});

/**
 * Pushes one event through the real simulator adapter and the real ingest
 * action — the exact path App\Http\Controllers\Devices\DeviceSimulatorController
 * takes when an operator presses the button.
 */
function simulateSwipe(object $test, int $nativeEventId, string $direction, Carbon $at): RawAccessEvent
{
    $payload = app(SimulatorDeviceAdapter::class)->generateEventPayload(
        device: $test->device,
        nativeEventId: $nativeEventId,
        streamEpoch: 0,
        cardHex: $test->credential->card_hex,
        cardType: $test->credential->card_type,
        direction: $direction,
    );

    $payload['raw_device_time'] = $at->toIso8601String();

    $event = app(IngestRawAccessEventAction::class)->execute($test->device, $payload);

    // The adapter cannot control the timestamps the ingest action normalises,
    // and the row is immutable by design, so the clock is set directly here
    // to put the swipe inside the day under test.
    RawAccessEvent::query()->whereKey($event->id)->toBase()->update([
        'normalized_event_time_utc' => $at,
        'received_at' => $at,
        'credential_id' => $test->credential->id,
    ]);

    return $event->fresh();
}

test('an event generated by the in-app simulator identifies itself as simulated', function () {
    $event = simulateSwipe($this, 1, 'in', $this->day->copy()->setTime(9, 0));

    // The column, not just a marker buried in the JSON payload: this is what
    // every query downstream can actually filter on.
    expect($event->ingestion_source)->toBe(RawAccessEvent::SOURCE_SIMULATOR)
        ->and($event->payload['source'])->toBe('simulator');
});

test('a full simulated day produces no attendance session at all', function () {
    simulateSwipe($this, 1, 'in', $this->day->copy()->setTime(9, 0));
    simulateSwipe($this, 2, 'out', $this->day->copy()->setTime(18, 0));

    expect(($this->reconstruct)())->toHaveCount(0);
});

test('a real badge read on the same day still produces a paid session', function () {
    // Without this the test above would pass just as happily if
    // reconstruction were broken outright, which would prove nothing.
    RawAccessEvent::factory()->create([
        'organization_id' => $this->organization->id,
        'device_id' => $this->device->id,
        'credential_id' => $this->credential->id,
        'native_event_id' => 11,
        'reader_direction_snapshot' => 'in',
        'normalized_event_time_utc' => $this->day->copy()->setTime(9, 0),
        'received_at' => $this->day->copy()->setTime(9, 0),
    ]);
    RawAccessEvent::factory()->create([
        'organization_id' => $this->organization->id,
        'device_id' => $this->device->id,
        'credential_id' => $this->credential->id,
        'native_event_id' => 12,
        'reader_direction_snapshot' => 'out',
        'normalized_event_time_utc' => $this->day->copy()->setTime(18, 0),
        'received_at' => $this->day->copy()->setTime(18, 0),
    ]);

    $sessions = ($this->reconstruct)();

    expect($sessions)->toHaveCount(1)
        ->and($sessions[0]->fresh()->raw_duration_minutes)->toBe(540);
});

test('simulated swipes cannot pad a real day', function () {
    // The real day is 09:00-13:00. A simulated "out" at 18:00 must not be
    // able to stretch it, and a simulated "in" must not open a second one.
    RawAccessEvent::factory()->create([
        'organization_id' => $this->organization->id,
        'device_id' => $this->device->id,
        'credential_id' => $this->credential->id,
        'native_event_id' => 21,
        'reader_direction_snapshot' => 'in',
        'normalized_event_time_utc' => $this->day->copy()->setTime(9, 0),
        'received_at' => $this->day->copy()->setTime(9, 0),
    ]);
    RawAccessEvent::factory()->create([
        'organization_id' => $this->organization->id,
        'device_id' => $this->device->id,
        'credential_id' => $this->credential->id,
        'native_event_id' => 22,
        'reader_direction_snapshot' => 'out',
        'normalized_event_time_utc' => $this->day->copy()->setTime(13, 0),
        'received_at' => $this->day->copy()->setTime(13, 0),
    ]);

    simulateSwipe($this, 23, 'in', $this->day->copy()->setTime(14, 0));
    simulateSwipe($this, 24, 'out', $this->day->copy()->setTime(18, 0));

    $sessions = ($this->reconstruct)();

    expect($sessions)->toHaveCount(1)
        ->and($sessions[0]->fresh()->raw_duration_minutes)->toBe(240);
});

test('the exclusion really works on PostgreSQL, not just on the SQLite suite', function () {
    // Audit A02 is the reason this test exists: a query that SQLite accepts
    // can fail or behave differently on PostgreSQL, and that one reached
    // production. This filter decides what becomes paid time, so it is
    // verified against the real database and the real json-path operator
    // rather than assumed to translate.
    Artisan::call('migrate', ['--database' => 'pgsql_rls_test', '--force' => true]);

    $connection = DB::connection('pgsql_rls_test');
    $connection->beginTransaction();

    try {
        $organizationId = (string) Str::uuid();
        $connection->table('organizations')->insert([
            'id' => $organizationId,
            'name' => 'Simulator isolation probe',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $connection->statement("select set_config('app.current_org_id', ?, true)", [$organizationId]);

        $siteId = (string) Str::uuid();
        $connection->table('sites')->insert([
            'id' => $siteId,
            'organization_id' => $organizationId,
            'name' => 'Probe site',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $deviceId = (string) Str::uuid();
        $connection->table('devices')->insert([
            'id' => $deviceId,
            'organization_id' => $organizationId,
            'site_id' => $siteId,
            'serial_number' => 'PROBE-'.substr($deviceId, 0, 8),
            'model' => 'XPass 2',
            'status' => 'online',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $rows = [
            ['source' => RawAccessEvent::SOURCE_SIMULATOR, 'payload' => '{}'],
            ['source' => RawAccessEvent::SOURCE_DEVICE_CONNECTOR, 'payload' => '{"source":"simulator"}'],
            ['source' => RawAccessEvent::SOURCE_DEVICE_CONNECTOR, 'payload' => '{}'],
            ['source' => RawAccessEvent::SOURCE_BIOSTAR_IMPORT, 'payload' => '{"source":"biostar"}'],
        ];

        foreach ($rows as $index => $row) {
            $connection->table('raw_access_events')->insert([
                'id' => (string) Str::uuid(),
                'organization_id' => $organizationId,
                'device_id' => $deviceId,
                'native_event_id' => 900 + $index,
                'stream_epoch' => 0,
                'raw_device_time' => now(),
                'normalized_event_time_utc' => now(),
                'received_at' => now(),
                'event_code' => 'access_granted',
                'reader_direction_snapshot' => 'in',
                'payload' => $row['payload'],
                'ingestion_source' => $row['source'],
                'created_at' => now(),
            ]);
        }

        // Two layers scope this read and both have to be pointed at the probe
        // organization: Postgres RLS via the GUC set above, and Eloquent's own
        // BelongsToOrganization scope via CurrentOrganization.
        CurrentOrganization::set($organizationId);

        $kept = RawAccessEvent::on('pgsql_rls_test')->excludingSimulated()->count();

        CurrentOrganization::set($this->organization->id);

        // Two of the four are simulated — one by its column, one by the
        // payload marker only — so exactly two survive.
        expect($kept)->toBe(2);
    } finally {
        $connection->rollBack();
    }
});

test('rows written before the column was fixed are still recognised by their payload marker', function () {
    // This table is append-only by design, so events the in-app simulator
    // produced while it stamped `device-connector` can never be re-tagged.
    // The marker the simulator has always written into the payload is the
    // only honest way left to recognise them — and it is a fact recorded at
    // ingestion, not an inference.
    foreach ([['in', 9], ['out', 18]] as $index => [$direction, $hour]) {
        RawAccessEvent::factory()->create([
            'organization_id' => $this->organization->id,
            'device_id' => $this->device->id,
            'credential_id' => $this->credential->id,
            'native_event_id' => 31 + $index,
            'reader_direction_snapshot' => $direction,
            'normalized_event_time_utc' => $this->day->copy()->setTime($hour, 0),
            'received_at' => $this->day->copy()->setTime($hour, 0),
            'ingestion_source' => RawAccessEvent::SOURCE_DEVICE_CONNECTOR,
            'payload' => ['source' => 'simulator', 'generated_at' => now()->toIso8601String()],
        ]);
    }

    expect(($this->reconstruct)())->toHaveCount(0);
});
