<?php

/**
 * Shared / Foundation-owned Inertia web routes.
 *
 * This is the "Shared" module per docs/architecture.md §2 — cross-cutting,
 * Foundation/Integration-owned only. It carries the routes generated by the
 * official Laravel Vue starter kit (welcome, dashboard, settings, passkeys)
 * plus anything else that doesn't belong to a specific business module.
 *
 * Every other module gets its own routes/modules/web-<module>.php file and
 * must NOT add routes here. See docs/architecture.md §3.1.
 */

use Illuminate\Support\Facades\Route;

Route::inertia('/', 'Welcome')->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::inertia('dashboard', 'Dashboard')->name('dashboard');
});

require __DIR__.'/../settings.php';
