<?php

/**
 * Shared / Foundation-owned Inertia web routes.
 *
 * This is the "Shared" module per docs/architecture.md §2 — cross-cutting,
 * Foundation/Integration-owned only. It carries the routes generated by the
 * official Laravel Vue starter kit (welcome, dashboard, settings, passkeys)
 * plus anything else that doesn't belong to a specific business module.
 *
 * Every other module gets its own routes/modules/web-<module>.php file and
 * must NOT add routes here. See docs/architecture.md §3.1.
 */

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\MyDayController;
use App\Http\Controllers\MyProfileController;
use Illuminate\Support\Facades\Route;

// The starter kit's default "Welcome" marketing page is not a real screen of
// this product — root now redirects straight to the app (dashboard when
// authenticated, login otherwise) instead of showing Laravel boilerplate.
Route::get('/', fn () => auth()->check() ? to_route('dashboard') : to_route('login'))->name('home');

// OPS-01: /health is a cheap, public liveness probe (no auth middleware —
// an external load balancer/uptime checker hits this directly). /ready is
// deliberately NOT wrapped in 'auth' middleware either — HealthController::ready()
// does its own is_platform_admin check and returns a clean JSON 403 for
// anyone else, rather than redirecting an API-style caller to an HTML login
// page the way 'auth' middleware would.
Route::get('health', [HealthController::class, 'health'])->name('health');
Route::get('ready', [HealthController::class, 'ready'])->name('ready');

Route::middleware(['auth', 'verified'])->group(function () {
    // Real Projects/Tasks-backed dashboard — see App\Http\Controllers\DashboardController.
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Every user's own work profile — see App\Http\Controllers\MyProfileController's
    // docblock for why it is deliberately never permission-gated beyond auth.
    Route::get('me/profile', [MyProfileController::class, 'show'])->name('me.profile');

    // Reserved mobile bottom-nav slot "დღეს" (lib/mobileNav.ts). WORKER-01:
    // real Tasks-backed data via App\Http\Controllers\MyDayController — the
    // static placeholder (docs/decisions.md DEC-050) is retired.
    Route::get('my-day', [MyDayController::class, 'index'])->name('my-day');

    // PWA-01: dismiss a `for_review` OfflineSyncSubmission the current user
    // can see on their own My Day page — acknowledgement only, never
    // reprocesses the original action.
    Route::post('my-day/offline-review/{submission}/acknowledge', [MyDayController::class, 'acknowledgeOfflineReview'])
        ->name('my-day.offline-review.acknowledge');
});

if (app()->environment(['local', 'testing'])) {
    // QA-only aliases (no auth) so a headless browser can screenshot the
    // real page components at multiple viewport widths without needing a
    // logged-in session — see docs/decisions.md DEC-050. Never registered
    // outside local/testing; render the identical Dashboard/MyDay page
    // components used by the real, auth-gated routes above.
    Route::inertia('design-system/dashboard', 'Dashboard')->name('design-system.dashboard');
    Route::inertia('design-system/my-day', 'MyDay')->name('design-system.my-day');
}

require __DIR__.'/../settings.php';
