<?php

/**
 * Shared / Foundation-owned Inertia web routes.
 *
 * This is the "Shared" module per docs/architecture.md §2 — cross-cutting,
 * Foundation/Integration-owned only. It carries the routes generated by the
 * official Laravel Vue starter kit (welcome, dashboard, settings, passkeys)
 * plus anything else that doesn't belong to a specific business module.
 *
 * Every other module gets its own routes/modules/web-<module>.php file and
 * must NOT add routes here. See docs/architecture.md §3.1.
 */

use Illuminate\Support\Facades\Route;

Route::inertia('/', 'Welcome')->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::inertia('dashboard', 'Dashboard')->name('dashboard');

    // Reserved mobile bottom-nav slot "დღეს" (lib/mobileNav.ts). Placeholder
    // composition owned by Shared/Foundation until Tasks/Attendance wire
    // real data in — see docs/decisions.md DEC-050.
    Route::inertia('my-day', 'MyDay')->name('my-day');
});

if (app()->environment(['local', 'testing'])) {
    // QA-only aliases (no auth) so a headless browser can screenshot the
    // real page components at multiple viewport widths without needing a
    // logged-in session — see docs/decisions.md DEC-050. Never registered
    // outside local/testing; render the identical Dashboard/MyDay page
    // components used by the real, auth-gated routes above.
    Route::inertia('design-system/dashboard', 'Dashboard')->name('design-system.dashboard');
    Route::inertia('design-system/my-day', 'MyDay')->name('design-system.my-day');
}

require __DIR__.'/../settings.php';
